//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medpolis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Clinica_MedpolisEntities : DbContext
    {
        public Clinica_MedpolisEntities()
            : base("name=Clinica_MedpolisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Concediu> Concediu { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Programare> Programare { get; set; }
        public virtual DbSet<Serviciu> Serviciu { get; set; }
        public virtual DbSet<Specialitate> Specialitate { get; set; }
    }
}
