//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medpolis
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Programare
    {
        public int ID { get; set; }
        public int ID_Client { get; set; }
        public int ID_Serviciu { get; set; }
        public int ID_Doctor { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Serviciu Serviciu { get; set; }
    }
}
