//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medpolis
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Serviciu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Serviciu()
        {
            this.Programare = new ObservableCollection<Programare>();
        }
    
        public int ID { get; set; }
        public string Denumire { get; set; }
        public int Pret { get; set; }
        public int ID_Specialitate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Programare> Programare { get; set; }
        public virtual Specialitate Specialitate { get; set; }
    }
}
